### ISSUE TITLE
does not work when app start in PROD mode

### ISSUE THREAD

**Issue by greenlaw110** [actframework/act-ebean2#2]
When I start the app in PROD mode I get the following error:

```
java.lang.IllegalStateException: Bean class demo.todo.ebean.TodoItem is not enhanced?
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.setEntityBeanClass(BeanDescriptorManager.java:1421)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.createByteCode(BeanDescriptorManager.java:1293)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.readDeployAssociations(BeanDescriptorManager.java:1215)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityDeploymentAssociations(BeanDescriptorManager.java:718)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:325)
	at io.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:141)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:130)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:44)
	at io.ebean.EbeanServerFactory.createInternal(EbeanServerFactory.java:108)
	at io.ebean.EbeanServerFactory.create(EbeanServerFactory.java:67)
	at act.db.ebean2.EbeanService.configured(EbeanService.java:64)
	at act.db.sql.SqlDbService$1.run(SqlDbService.java:35)
	at act.job._Job$2.apply(_Job.java:291)
	at act.job._Job.doJob(_Job.java:253)
	at act.job._Job.run(_Job.java:193)
	at act.job._Job$LockableJobList.runSubJobs(_Job.java:75)
	at act.job._Job.runPrecedenceJobs(_Job.java:268)
	at act.job._Job.run(_Job.java:188)
	at act.job.AppJobManager$_AppEventListener.on(AppJobManager.java:313)
	at act.event.EventBus.callOn(EventBus.java:230)
	at act.event.EventBus.callOn(EventBus.java:254)
	at act.event.EventBus.callOn(EventBus.java:275)
	at act.event.EventBus.emit(EventBus.java:296)
	at act.event.EventBus.emit(EventBus.java:284)
	at act.app.App.emit(App.java:825)
	at act.app.App.refresh(App.java:586)
	at act.app.AppManager.load(AppManager.java:83)
	at act.app.AppManager$_F$1.visit(AppManager.java:155)
	at act.app.AppManager$_F$1.visit(AppManager.java:151)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2226)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2216)
	at act.app.AppScanner.scan(AppScanner.java:94)
	at act.app.AppScanner.scan(AppScanner.java:74)
	at act.app.AppManager.loadSingleApp(AppManager.java:61)
	at act.Act.start(Act.java:319)
	at act.Act.startApp(Act.java:290)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at act.boot.app.RunApp.start(RunApp.java:84)
	at act.Act.start(Act.java:631)
```

However I don't have the issue when starting app in DEV mode

**Comment by greenlaw110** [comment]
Fixed in 1.0.2
