### ISSUE TITLE
Error connecting to mysql database

### ISSUE THREAD

**Issue by greenlaw110** [actframework/act-ebean2#29]
```properties
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://rdskxxxxxxxf1111111.mysql.rds.aliyuncs.com:3306/aaa?useUnicode=true&characterEncoding=UTF-8&useSSL=false
db.username=aaa
db.password=password
db.ddl.generate=false
db.ddl.run=false
db.ddl.update=false
#db.ddl.create=true
```

```
2018-11-21 08:38:35,396 ERROR o.a.d.p.ConnectionPool@[main] [org.avaje.datasource.pool.ConnectionPool] - FATAL: DataSourcePool [default] is down or has network error!!!
2018-11-21 08:38:35,396 INFO o.a.d.p.PooledConnectionQueue@[main] [org.avaje.datasource.pool.PooledConnectionQueue] - Reseting DataSourcePool [default] min[2] max[10] free[0] busy[0] waiting[0] highWaterMark[0] waitCount[0] hitCount[0]
2018-11-21 08:38:35,397 INFO
o.a.d.p.PooledConnectionQueue@[main]
[org.avaje.datasource.pool.PooledConnectionQueue] - Busy Connections: 2018-11-21 08:38:35,398 INFO a.a.App@[Thread-4] 
[act.app.App] - App shutting down ....
Exception in thread "main"
org.osgl.exception.ConfigurationException: Error init
SQL db service
at org.osgl.util.E.invalidConfiguration(E.java:300)
at act.db.sql.SqlDbService.init(SqlDbService.java:
149)
at act.db.sql.SqlDbService$1.run(SqlDbService.java:76)
at act.job.Job$4.apply(Job.java:440)
at act.job.Job.doJob(Job.java:401)
at act.job.Job.run(Job.java:338)
at act.job.Job$LockableJobList.runSubJobs(Job.java:112)
at act.job.Job$LockableJobList.runSubJobs(Job.java:93)
at act.job.Job.runFollowingJobs(Job.java:421)
at act.job.Job.run(Job.java:390)
at act.job.JobManager$_SysEventListener.on(JobManager. java:450)
at act.event.EventBus.callOn(EventBus.java:1310)
at act.event.EventBus.callOn(EventBus.java:1332)
at act.event.EventBus.callOn(EventBus.java:1362)
at act.event.EventBus._emit(EventBus.java:1223)at act.event.EventBus.emit(EventBus.java:679)
at act.app.App.emit(App.java:1240)
at act.app.App.refresh(App.java:733)
at act.app.AppManager.load(AppManager.java:75)
at act.app.AppManager$_F$1.visit(AppManager.java:143)
at act.app.AppManager$_F$1.visit(AppManager.java:139)
at org.osgl.Lang$Visitor.apply(Lang.java:2460)
at org.osgl.Lang$Visitor.apply(Lang.java:2450)
at act.app.AppScanner.scan(AppScanner.java:91)
at act.app.AppScanner.scan(AppScanner.java:71)
at act.app.AppManager.loadSingleApp(AppManager.java:53)
at act.Act.startup(Act.java:300)
at act.Act.startup(Act.java:1181)
at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethod)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.osgl.Lang.invokeStatic(Lang.java:7983)
at act.Act.bootstrap(Act.java:1087)
at act.Act.start(Act.java:637)
at cn.com.huiyongche.AppEntry.main(AppEntry.java:39)
Caused by: java.lang.RuntimeException:
java.sql.SQLException: The user specified as a definer ('jiayou'@'172.17.11.169') does not exist
at org.avaje.datasource.pool.ConnectionPool.<init>(ConnectionPool.java:232)
at org.avaje.datasource.core.Factory.createPool(Factory.java:15)at
act.db.ebean.util.EbeanDataSourceProvider.createDataSource(EbeanDataSourceProvider.java:65)
at act.db.sql.SqlDbService.doInitDataSource(SqlDbService.java:270)
at act.db.sql.SqlDbService.initDataSource(SqlDbService.java:253)
at act.db.sql.SqlDbService.init(SqlDbService.java:118)
... 34 more
Caused by: java.sql.SQLException: The user specifiedas a definer ('jiayou'@'172.17.11.169') does not exist
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:127)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:862)
at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:444)
at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:230)
at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:226)
at java.sql.DriverManager.getConnection(DriverManager.java:664)
at java.sql.DriverManager.getConnection(DriverManager.java:208)
at or .avaje.datasource.pool.ConnectionPool.createUnpooledConnection(ConnectionPool.java:432)
at org.avaje.datasource.pool.ConnectionPool.createConne
ctionForQueue(ConnectionPool.java:668)
at
org.avaje.datasource.pool.PooledConnectionQueue.ensureMinimumConnections(PooledConnectionQueue.java:228)
at org.avaje.datasource.pool.ConnectionPool.initialise(ConnectionPool.java:275)
at org.avaje.datasource.pool.ConnectionPool.<init>(ConnectionPool.java:225)
... 39 more
Exception in thread "Thread-5"
java.lang.NullPointerException
at act.Act.shutdownNetworkLayer(Act.java:1047)
at act.Act.shutdownAct(Act.java:1097)
at act.Act.access$200(Act.java:83)
at act.Act$2.run(Act.java:342)
```

**Comment by wwwhehehe** [comment]
大佬，这个错误的原因是什么？怎么解决呢？
