### ISSUE TITLE
It doesn't start with MySQL jdbc driver 5.x

### ISSUE THREAD

**Issue by greenlaw110** [actframework/act-ebean2#3]
**Error stack**

```
java.lang.IllegalStateException: Problem loading Database Driver [com.mysql.cj.jdbc.Driver]: com.mysql.cj.jdbc.Driver
	at org.avaje.datasource.pool.ConnectionPool.initialise(ConnectionPool.java:257)
	at org.avaje.datasource.pool.ConnectionPool.<init>(ConnectionPool.java:222)
	at org.avaje.datasource.Factory.createPool(Factory.java:12)
	at io.ebeaninternal.server.core.DefaultContainer.getDataSourceFromConfig(DefaultContainer.java:310)
	at io.ebeaninternal.server.core.DefaultContainer.setDataSource(DefaultContainer.java:265)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:108)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:44)
	at io.ebean.EbeanServerFactory.createInternal(EbeanServerFactory.java:108)
	at io.ebean.EbeanServerFactory.create(EbeanServerFactory.java:67)
	at act.db.ebean2.EbeanService.configured(EbeanService.java:70)
	at act.db.sql.SqlDbService$1.run(SqlDbService.java:35)
	at act.job._Job$2.apply(_Job.java:291)
	at act.job._Job.doJob(_Job.java:253)
	at act.job._Job.run(_Job.java:193)
	at act.job._Job$LockableJobList.runSubJobs(_Job.java:75)
	at act.job._Job.runPrecedenceJobs(_Job.java:268)
	at act.job._Job.run(_Job.java:188)
	at act.job.AppJobManager$_AppEventListener.on(AppJobManager.java:313)
	at act.event.EventBus.callOn(EventBus.java:230)
	at act.event.EventBus.callOn(EventBus.java:254)
	at act.event.EventBus.callOn(EventBus.java:275)
	at act.event.EventBus.emit(EventBus.java:296)
	at act.event.EventBus.emit(EventBus.java:284)
	at act.app.App.emit(App.java:825)
	at act.app.App.refresh(App.java:586)
	at act.app.AppManager.load(AppManager.java:83)
	at act.app.AppManager$_F$1.visit(AppManager.java:155)
	at act.app.AppManager$_F$1.visit(AppManager.java:151)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2226)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2216)
	at act.app.AppScanner.scan(AppScanner.java:94)
	at act.app.AppScanner.scan(AppScanner.java:74)
	at act.app.AppManager.loadSingleApp(AppManager.java:61)
	at act.Act.start(Act.java:319)
	at act.Act.startApp(Act.java:290)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at act.boot.app.RunApp.start(RunApp.java:84)
	at act.boot.app.RunApp.start(RunApp.java:62)
	at com.techempower.act.AppEntry.main(AppEntry.java:39)
Caused by: java.lang.ClassNotFoundException: com.mysql.cj.jdbc.Driver
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at act.boot.app.FullStackAppBootstrapClassLoader.loadClass(FullStackAppBootstrapClassLoader.java:311)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.avaje.datasource.pool.ConnectionPool.initialise(ConnectionPool.java:252)
	... 41 more
```

**Comment by greenlaw110** [comment]
Caused by https://github.com/actframework/act-sql-common/issues/2
