### ISSUE TITLE
NPE when no third party datasource configured

### ISSUE THREAD

**Issue by greenlaw110** [actframework/act-ebean2#6]
Error stack:

```
java.lang.NullPointerException: null
	at act.db.ebean2.EbeanService.createDataSource(EbeanService.java:76)
	at act.db.sql.SqlDbService.initDataSource(SqlDbService.java:93)
	at act.db.sql.SqlDbService.access$000(SqlDbService.java:23)
	at act.db.sql.SqlDbService$1.run(SqlDbService.java:36)
	at act.job._Job$2.apply(_Job.java:291)
	at act.job._Job.doJob(_Job.java:253)
	at act.job._Job.run(_Job.java:193)
	at act.job._Job$LockableJobList.runSubJobs(_Job.java:75)
	at act.job._Job.runPrecedenceJobs(_Job.java:268)
	at act.job._Job.run(_Job.java:188)
	at act.job.AppJobManager$_AppEventListener.on(AppJobManager.java:313)
	at act.event.EventBus.callOn(EventBus.java:230)
	at act.event.EventBus.callOn(EventBus.java:254)
	at act.event.EventBus.callOn(EventBus.java:275)
	at act.event.EventBus.emit(EventBus.java:296)
	at act.event.EventBus.emit(EventBus.java:284)
	at act.app.App.emit(App.java:828)
	at act.app.App.refresh(App.java:586)
	at act.app.AppManager.load(AppManager.java:83)
	at act.app.AppManager$_F$1.visit(AppManager.java:155)
	at act.app.AppManager$_F$1.visit(AppManager.java:151)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2226)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2216)
	at act.app.AppScanner.scan(AppScanner.java:94)
	at act.app.AppScanner.scan(AppScanner.java:74)
	at act.app.AppManager.loadSingleApp(AppManager.java:61)
	at act.Act.start(Act.java:319)
	at act.Act.startApp(Act.java:290)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at act.boot.app.RunApp.start(RunApp.java:84)
	at act.boot.app.RunApp.start(RunApp.java:62)
	at act.Act.start(Act.java:640)
	at com.yabonza.Yabonza.main(Yabonza.java:19)
```

**Comment by greenlaw110** [comment]
fixed in 1.0.4
